### ISSUE TITLE
Is it possible to add additional sliders to Iced Mocha Theme?

### ISSUE THREAD

**Issue by joemang1969** [eventespresso/iced-mocha#14]
I would like 7 or 8 rotating images but there are only space for 5 slides in the custom format?

Can anyone help me with making a total of 8 slides in this theme?

**Comment by sethshoultes** [comment]
@joemang1969 you can add more default slides by editing this file: https://github.com/eventespresso/iced-mocha/blob/master/admin/defaults.php

See lines 36-55

**Comment by joemang1969** [comment]
Thanks Seth,
Unfortunately it did not work, and then I tried to examine the code and noticed the default number of slides and updated that to 9  but it still did not work??

another thing is that it does not add additional dots in the center bottom of the home page slider and it does not add the options to add the custom slides in the presentation settings.

attached are 2 screenshots  thanks for your help..

![defaultphp](https://cloud.githubusercontent.com/assets/11142210/6344357/670382e2-bbc5-11e4-9351-e923ab7178b6.jpg)
![slides](https://cloud.githubusercontent.com/assets/11142210/6344362/75e62b3e-bbc5-11e4-9718-47fd2200ebc5.jpg)

**Comment by sethshoultes** [comment]
@joemang1969 I increased the default slide count to 10. Does that help?

**Comment by joemang1969** [comment]
Hi Seth, I'm still having issues with the slides,  I added a question to another thread somewhere?

**Comment by joemang1969** [comment]
Thanks Seth, but it still does not work on home page it only goes through the 5 slides and then repeats... it also only has 5 little buttons as pictured, but the control panel for iced mocha settings does now have 10 options for the slides so its definitely a step towards what we are trying to achieve.

**Comment by joemang1969** [comment]
there is an image here https://github.com/eventespresso/iced-mocha/commit/cd4bcf0ce85a983785b59ede7eaf3caabd8f8184

**Comment by ejbaum** [comment]
This still only shows 5 slides when the GUI allows 10.

**Comment by joemang1969** [comment]
Yes it does not work as it is here but I recently got a fix.   Will post soon.

**Comment by ejbaum** [comment]
sweet
