### ISSUE TITLE
getting fatal error trying to add widgets

### ISSUE THREAD

**Issue by joemang1969** [eventespresso/iced-mocha#16]
Fatal error: Class 'EE_Registry' not found in /home/cmunday/clairescreativeadventures.com/wp-content/themes/iced-mocha-master/includes/widgets.php on line 147

Can anyone help with this??

**Comment by joemang1969** [comment]
website is http://www.clairescreativeadventures.com

**Comment by sethshoultes** [comment]
Hello Joe,

What version of EE4 do you currently have installed?

**Comment by tn3rb** [comment]
Is Event Espresso active on that site?
I can't find it anywhere...
The base EE resources are always loaded in the admin so there is no reason that EE_Registry shouldn't be available to the widget... unless EE is deactivated.

Beyond that... I would need access to your site to investigate further
