### ISSUE TITLE
Increased the default slide count to 10. Fixes #14  does not work

### ISSUE THREAD

**Issue by joemang1969** [eventespresso/iced-mocha#19]
Thanks Seth, but it still does not work on home page it only goes through the 5 slides and then repeats... it also only has 5 little buttons as pictured,  but the control panel for iced mocha settings does now have 10 options for the slides so its definitely a step towards what we are trying to achieve.

![untitled](https://cloud.githubusercontent.com/assets/11142210/6818507/83be95ec-d287-11e4-8edd-c28b1d50af72.jpg)

Would be great if the little buttons were numbers instead?  that could go anywhere from 1-10 ???

**Comment by joemang1969** [comment]
https://github.com/eventespresso/iced-mocha/commit/cd4bcf0ce85a983785b59ede7eaf3caabd8f8184#diff-aadcaadf90c12018b64f9ab1600284b6

**Comment by sethshoultes** [comment]
Hey Joe,

Sorry it's been so ling. I had some health issues that kept me tied up. I recently updated the theme, please check it out here:
https://github.com/eventespresso/iced-mocha/archive/1.0.4.zip

**Comment by joemang1969** [comment]
[iced-mocha-master.zip](https://github.com/eventespresso/iced-mocha/files/63429/iced-mocha-master.zip)
Thanks Seth,
Sorry to hear about your Health issues.... As I did not hear from you I ended up hiring a freelance person to do the code work.  This theme has 10 sliders and options for 15 social network buttons

**Comment by joemang1969** [comment]
not sure how they differ but will check it out ... Good to have you back..

**Comment by sethshoultes** [comment]
The new version adds support for the WP admin settings page that was broken in WordPress 4.4.
