### ISSUE TITLE
Would like to hide pricing event espresso?  

### ISSUE THREAD

**Issue by joemang1969** [eventespresso/iced-mocha#20]
I've used number of different css variations in My custom css , the child theme and iced mocha settings  nothing seems to work to hide the pricing

 I have a client that does not want to show pricing on event pages or anywhere for that matter. she wants to have people pre-register for classes with all the form info, then when approved for registration, send an invoice for the amount so people can pay online?
How can this be achieved? is it possible? what type of work around could be done? I thought maybe a small pre registration of say $10 then send a higher invoice for the entire semester of classes upon approval? or even a zero cost pre-registration?

I’ve added all these variations of css into my custom css as well as the child theme and nothing seems to get the prices to disappear??
.event_prices, .event_price, .price {
display: none;
}
/* hide the event price in the event list */
p.event_price {display:none;}
/* hide the event price in the registration form */
p.event_prices {display:none;}
/* Remove price on event list. */
.event_price {
display: none;
}

**Comment by lorenzocaum** [comment]
Please see the following support post:

https://eventespresso.com/topic/hidden-pricing-delayed-invoice-with-online-payments/
