### ISSUE TITLE
Select quantity column of EE4 ticket selector cut off on small screens

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/iced-mocha#28]
If the Event Espresso > Events > Templates settings are set to Show Ticket Details? Yes, then the Select quantity column gets pushed off the screen.

![Screenshot 3:8:17, 10:55 AM.jpg](https://s4.postimg.org/j309g5xgt/Screenshot_3_8_17_10_55_AM.jpg)

**Comment by joemang1969** [comment]
Thanks Josh,My Client just pointed this out to me, it does show if the screen is held horizontal but would be great to fix this some way?
